//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGCGM.Lang {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGCGM.Lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El backup ya existe en la pestaña &quot;{0}&quot;..
        /// </summary>
        internal static string ADD_BACKUP_EXIST_IN_TAB {
            get {
                return ResourceManager.GetString("ADD_BACKUP_EXIST_IN_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el directorio que contiene los backups de juegos GameCube..
        /// </summary>
        internal static string ADD_SELECT_DIRECTORY {
            get {
                return ResourceManager.GetString("ADD_SELECT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un backup de juego GameCube para agregar en la aplicación..
        /// </summary>
        internal static string ADD_SELECT_GAME {
            get {
                return ResourceManager.GetString("ADD_SELECT_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los archivos.
        /// </summary>
        internal static string ALL_FILES {
            get {
                return ResourceManager.GetString("ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}-{1}.
        /// </summary>
        internal static string CONST_BACKUP_ID {
            get {
                return ResourceManager.GetString("CONST_BACKUP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ({1}).
        /// </summary>
        internal static string CONST_DRIVE_FULLNAME {
            get {
                return ResourceManager.GetString("CONST_DRIVE_FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log.
        /// </summary>
        internal static string CONST_LOG {
            get {
                return ResourceManager.GetString("CONST_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log (*).
        /// </summary>
        internal static string CONST_LOG_CHANGED {
            get {
                return ResourceManager.GetString("CONST_LOG_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directorio movido o eliminado..
        /// </summary>
        internal static string DIRECTORY_MOVED_OR_DELETED_POINT {
            get {
                return ResourceManager.GetString("DIRECTORY_MOVED_OR_DELETED_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo dispositivo detectado..
        /// </summary>
        internal static string LOG_DEVICE_DETECTED {
            get {
                return ResourceManager.GetString("LOG_DEVICE_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo no preparado, no se encontro el directorio &quot;{0}&quot;..
        /// </summary>
        internal static string LOG_DEVICE_NOT_PREPARED {
            get {
                return ResourceManager.GetString("LOG_DEVICE_NOT_PREPARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo preparado correctamente.
        /// </summary>
        internal static string LOG_DEVICE_PREPARED_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_DEVICE_PREPARED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El dispositivo &quot;{0}&quot; no esta preparado para contener backups de juegos GameCube. ¿Desea crear el directorio &quot;{1}&quot;?.
        /// </summary>
        internal static string MSG_DEVICE_NOT_PREPARED_QUESTION {
            get {
                return ResourceManager.GetString("MSG_DEVICE_NOT_PREPARED_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El dispositivo &quot;{0}&quot; ya no esta disponible..
        /// </summary>
        internal static string MSG_DEVICE_UNAVAILABLE {
            get {
                return ResourceManager.GetString("MSG_DEVICE_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo..
        /// </summary>
        internal static string READY_POINT {
            get {
                return ResourceManager.GetString("READY_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregando Backups:.
        /// </summary>
        internal static string STATUS_BACKUP_ADDING {
            get {
                return ResourceManager.GetString("STATUS_BACKUP_ADDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analizando directorio:.
        /// </summary>
        internal static string STATUS_DIRECTORY_ANALYZING {
            get {
                return ResourceManager.GetString("STATUS_DIRECTORY_ANALYZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analizando dispositivo:.
        /// </summary>
        internal static string STATUS_DRIVE_ANALYZING {
            get {
                return ResourceManager.GetString("STATUS_DRIVE_ANALYZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backup agregado correctamente..
        /// </summary>
        internal static string TASK_ADDBACKUP_ADDED_SUCESS {
            get {
                return ResourceManager.GetString("TASK_ADDBACKUP_ADDED_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analisis de Backup cancelado exitosamente..
        /// </summary>
        internal static string TASK_ADDBACKUP_CANCEL {
            get {
                return ResourceManager.GetString("TASK_ADDBACKUP_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banner no encontrado..
        /// </summary>
        internal static string TASK_ADDBACKUP_MISSING_BANNER {
            get {
                return ResourceManager.GetString("TASK_ADDBACKUP_MISSING_BANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analisis de directorio cancelado exitosamente..
        /// </summary>
        internal static string TASK_ADDDIRECTORY_CANCEL {
            get {
                return ResourceManager.GetString("TASK_ADDDIRECTORY_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se encontraron {0} backups..
        /// </summary>
        internal static string TASK_ADDDIRECTORY_FINDED_BACKUPS {
            get {
                return ResourceManager.GetString("TASK_ADDDIRECTORY_FINDED_BACKUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscando backups en directorio....
        /// </summary>
        internal static string TASK_ADDDIRECTORY_START {
            get {
                return ResourceManager.GetString("TASK_ADDDIRECTORY_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} detectado, buscando backups en directorio....
        /// </summary>
        internal static string TASK_ADDDIRECTORY_START_WITH_FILE {
            get {
                return ResourceManager.GetString("TASK_ADDDIRECTORY_START_WITH_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las caratulas del backup &quot;{0}&quot; ya existen, no es necesario descargarlas..
        /// </summary>
        internal static string TASK_DOWNLOAD_ALL_COVERS_EXIST {
            get {
                return ResourceManager.GetString("TASK_DOWNLOAD_ALL_COVERS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una descarga en progreso, para el backup &quot;{0}&quot;..
        /// </summary>
        internal static string TASK_DOWNLOAD_COVER_EXIST {
            get {
                return ResourceManager.GetString("TASK_DOWNLOAD_COVER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Montando dispositivo.
        /// </summary>
        internal static string TITLE_DEVICE_MOUNT {
            get {
                return ResourceManager.GetString("TITLE_DEVICE_MOUNT", resourceCulture);
            }
        }
    }
}
